"""empty message

Revision ID: 463b269f990e
Revises: cbead6d5e62f
Create Date: 2020-06-22 17:58:43.133110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '463b269f990e'
down_revision = 'cbead6d5e62f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
